### PR TITLE
much better

### PR DESCRIPTION
**Pull request by iJoshuaHD**

### CODE REVIEW

**Comment by TonyDroidd** [comment]
literally, much better ;)

**Comment by legoboy0215** [comment]
No. clearAll() is buggy.

**Comment by TonyDroidd** [comment]
It works fine, why you says is buggy? @legoboy0215

**Comment by ghost** [comment]
no it is not.

**Comment by legoboy0215** [comment]
When you have a empty inv. He knows that...

**Comment by ghost** [comment]
that is a simplified API to clear inventories. it doesnt matter if it's empty or not smart ass.

**Comment by legoboy0215** [comment]
Maybe for PM 1.5... because it had bugs with 1.4.1. And don't call me a 'smartass' cuz I am not smart.

**Comment by JackNoordhuis** [comment]
It's got a small bug, it doesn't check to make sure it's instanceof inventory before it clears it, this causes  an error as it tries to clear the inventory of a player that isn't online.

**Comment by legoboy0215** [comment]
Thanks owner.

**Comment by ghost** [comment]
@CrazedMiner you have to instanceof Player before you do that!

**Comment by ghost** [comment]
plus i use this method on my SG server. No errors are found.

**Comment by ghost** [comment]
Unless you dont check if the target is instanceof Player, it will obviously show error.

**Comment by ghost** [comment]
@legoboy0215 "Cause I am not smart" LMAO

**Pull request closed without merging**
